import { accounts, tokens, users } from './auth.ts'
import {
  billings,
  paymentMethodsRelations,
  paymentMethodTypeEnum,
  paymentMethods,
  payments,
  paymentsRelations,
  paymentStatusEnum,
  planIntervalEnum,
  plans,
  subscriptions,
  subscriptionsRelations,
  subscriptionStatusEnum,
  usageRecords,
  usageRecordsRelations,
} from './billings.ts'
import { applicants, demands } from './demands.ts'
import {
  accountProviderEnum,
  accountProviderZodEnum,
  demandCategoryEnum,
  demandCategoryZodEnum,
  demandPriorityEnum,
  demandPriorityZodEnum,
  demandStatusEnum,
  demandStatusZodEnum,
  roleEnum,
  roleZodEnum,
  tokenTypeEnum,
  tokenTypeZodEnum,
} from './enums.ts'
import { invites, members, organizations, units } from './organization.ts'

export const schema = {
  accounts,
  applicants,
  billings,
  demands,
  invites,
  members,
  organizations,
  tokens,
  units,
  users,
  plans,
  subscriptions,
  payments,
  paymentMethods,
  usageRecords,
  subscriptionsRelations,
  paymentsRelations,
  paymentMethodsRelations,
  usageRecordsRelations,
  accountProviderEnum,
  demandPriorityEnum,
  demandCategoryEnum,
  demandStatusEnum,
  tokenTypeEnum,
  roleEnum,
  planIntervalEnum,
  subscriptionStatusEnum,
  paymentStatusEnum,
  paymentMethodTypeEnum,
  roleZodEnum,
  tokenTypeZodEnum,
  accountProviderZodEnum,
  demandPriorityZodEnum,
  demandCategoryZodEnum,
  demandStatusZodEnum,
}
export type Schema = typeof schema
