@baseUrl = https://animated-spoon-4rg975jr4xxcj7pw-3333.app.github.dev
@organizationSlug = ubs
@tokenAuth = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYTQ1NjY0MC0xMmY3LTQ2ZGItYjk0ZC1mNjZlZGQ0N2NhNDUiLCJpYXQiOjE3NTUyODY3NTMsImV4cCI6MTc1NTg5MTU1M30.A6QbMso08eaqppLUxwWIcuSsGFmcRzR8jgrG8BMYFdg


###

# @name cria_novo_usuário
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Romerito",
  "email": "hugo1@gmail.com",
  "password": "romerito"
}

###

# @name retorna_todos_usuários
GET {{baseUrl}}/users
Authorization: {{tokenAuth}}

###

# @name autenticação_com_email_e_senha
POST {{baseUrl}}/sessions/password
Content-Type: application/json

{
  "email": "hugo1@gmail.com",
  "password": "romerito"
}

###

# @name cria_token_para_alterar_senha
POST {{baseUrl}}/password/recover
Content-Type: application/json

{
  "email": "hugo2@gmail.com"
}

###

# @name altera_senha
POST {{baseUrl}}/password/reset
Content-Type: application/json
 
{
  "code": "f890da11-565e-4f42-86b2-4dd51fcc17bf",
  "password": "romerito"
}


###

# @name retorna_informações_do_usuário_logado
GET {{baseUrl}}/profile
Authorization: {{tokenAuth}}


###

# @name cria_organização
POST {{baseUrl}}/organizations
Authorization: {{tokenAuth}}
Content-Type: application/json
 
{
  "name": "UBS"
}


###

# @name cria_unidade_em_uma_organização
POST {{baseUrl}}/organizations/{{organizationSlug}}/units
Authorization: {{tokenAuth}}
Content-Type: application/json
 
{
  "name": "Policlínica Barro Vermelho",
  "description": "Atendimento clinico",
  "location": "Santa Maria"
}


###

# @name atualiza_organização
PUT  {{baseUrl}}/organizations/{{organizationSlug}}
Authorization: {{tokenAuth}}
Content-Type: application/json
 
{
  "name": "usbsjs",
  "domain": "asafsad"
}



###

# @name retorna_unidades_de_uma_organização
GET {{baseUrl}}/organizations/{{organizationSlug}}/units
Authorization: {{tokenAuth}}

###

# @name retorna_informações_da_organização
GET {{baseUrl}}/organizations/{{organizationSlug}}
Authorization: {{tokenAuth}}

###

# @name retorna_organizações_do_usuário
GET {{baseUrl}}/organizations
Authorization: {{tokenAuth}}

###

# @name retorna_informações_de_membro_do_usuário
GET {{baseUrl}}/organizations/{{organizationSlug}}/membership
Authorization: {{tokenAuth}}

###

# @name retorna_informações_de_membro_do_usuário
GET {{baseUrl}}/organizations/{{organizationSlug}}/members
Authorization: {{tokenAuth}}

###

# @name retorna_informações_de_membro_do_usuário
GET {{baseUrl}}/organizations/{{organizationSlug}}/units/policlinica-barro-vermelho/members
Authorization: {{tokenAuth}}

###

# @name cria_convite
POST {{baseUrl}}/organizations/{{organizationSlug}}/invites
Authorization: {{tokenAuth}}
Content-Type: application/json
 
{
  "email": "hugo2@gmail.com",
  "role": "CLERK",
  "unitSlug": "policlinica-barro-vermelho"
}

###

# @name retorna_informações_de_membro_do_usuário
GET {{baseUrl}}/invites
Authorization: {{tokenAuth}}


###

# @name deleta_organização
DELETE  {{baseUrl}}/organizations/{{organizationSlug}}
Authorization: {{tokenAuth}}

###


# @name cria_convite
POST {{baseUrl}}/organizations/{{organizationSlug}}/applicants
Authorization: {{tokenAuth}}
Content-Type: application/json
 
{
  "name": "Hugo de Souza De Queiroz",
  "birthdate": "2000-11-21",
  "cpf": "20474669700",
  "phone": "1234567890",
  "mother": "as",
  "father": "as"
}

###

GET {{baseUrl}}/organizations/ubs/units/policlinica-barro-vermelho/demands?page=1&limit=20&sort_by=created_at&sort_order=desc
Authorization: {{tokenAuth}}


###

GET http://localhost:3333/organizations/ubs/units/policlinica-barro-vermelho/demands
Authorization: {{tokenAuth}}

###