services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: equipe-ativa-postgres
    environment:
      POSTGRES_DB: equipe_ativa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d equipe_ativa"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Cache Redis (opcional)
  redis:
    image: redis:7-alpine
    container_name: equipe-ativa-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
