version: '3.8'

services:
  postgres-test:
    image: postgres:15
    container_name: postgres-test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    command: postgres -c log_statement=all -c log_destination=stderr

volumes:
  postgres_test_data:
